name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # x11 server needed for png output lol
      - name: Setup xvfb (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
          # start xvfb in the background
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
      - name: Install openscad
        run: sudo apt-get install openscad
      - run: mkdir tests/output/
      - run: touch tests/empty.scad
      - run: 'openscad -o "tests/output/test.stl" "tests/test.scad"'
      - run: openscad tests/empty.scad -D 'color(0.5,0,0,0.5)import("test.stl");color(0,0.5,0,0.5)import("output/test.stl");' -o output.png
      # - run: du -B 1 output.stl
      - uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: output.png
      # - run: |
      #     git config --global user.name 'KeyV2 GHA Bot'
      #     git config --global user.email 'keyv2-gha-bot@users.noreply.github.com'
      #     git add -A
      #     git commit -m "Update test stls"
      #     git push
